# Generated by Django 5.2.7 on 2025-11-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_firstname', models.CharField(max_length=30)),
                ('checkout_lastname', models.CharField(max_length=3)),
                ('checkout_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_email', models.EmailField(max_length=254)),
                ('checkout_country', models.CharField(max_length=50)),
                ('checkout_town', models.CharField(max_length=255)),
                ('checkout_address', models.CharField(max_length=255)),
                ('checkout_zipcode', models.CharField(max_length=20)),
                ('checkout_phone_number', models.CharField(max_length=20)),
                ('checkout_order_comment', models.TextField(blank=True, null=True)),
                ('checkout_create_account', models.BooleanField(default=False)),
                ('checkout_ship_to_different_address', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
