# Generated by Django 5.2.7 on 2025-11-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checkout_ship_to_different_address',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_country',
            field=models.CharField(choices=[('USA', 'United States'), ('MEX', 'Mexico'), ('EGY', 'Egypt'), ('CAN', 'Canada'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('IND', 'India'), ('GER', 'Germany'), ('FRA', 'France'), ('JPN', 'Japan'), ('CHN', 'China'), ('BRA', 'Brazil')], max_length=50),
        ),
    ]
