# Generated by Django 5.2.7 on 2025-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_order_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymob_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
