"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
import dj_database_url
import psycopg2
from pathlib import Path
from decouple import config
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY', default=get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG= config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS=['*','furniture-ecommerce-production.up.railway.app','<prod DNS, host, and/or IP>']

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        'furniture-ecommerce-production.up.railway.app',
    ]

CSRF_TRUSTED_ORIGINS=[
    'https://furniture-ecommerce-production.up.railway.app/',
    'https://furniture-ecommerce-production.up.railway.app/admin/',
    'https://furniture-ecommerce-production.up.railway.app/shop/',
    'https://furniture-ecommerce-production.up.railway.app/shop/<int:pk>/',
    'https://furniture-ecommerce-production.up.railway.app/checkout/paymob/create/',
    'https://furniture-ecommerce-production.up.railway.app/accounts/login/',
    'https://furniture-ecommerce-production.up.railway.app/accounts/reset-password/',
    'https://furniture-ecommerce-production.up.railway.app/accounts/signup/',
    'https://furniture-ecommerce-production.up.railway.app/checkout/paymob/webhook/',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "whitenoise.runserver_nostatic",
    'products',
    'users',
    'payment',
    'rest_framework',
    'apis',
    'cloudinary',
    'cloudinary_storage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# MEDIA_URL = 'media/'
# MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [os.path.join(BASE_DIR / 'static')]
STATIC_ROOT = os.path.join(BASE_DIR / 'staticfiles')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('cloudinary_cloud_name'),
    'API_KEY': config('cloudinary_api_key'),
    'API_SECRET': config('cloudinary_api_secret'),
}

STORAGES = {
    "default": {
        "BACKEND": 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'users.CustomUser'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

PAYMOB_API_KEY = config('paymob_api_key')
PAYMOB_SECRET_KEY= config('paymob_secret_key')
PAYMOB_PUBLIC_KEY= config('paymob_public_key')
PAYMOB_INTEGRATION_ID= config('paymob_integration_id')
PAYMOB_IFRAME_BASE_URL= "https://accept.paymob.com/api/acceptance/iframes/982924"
PAYMOB_BASE_URL= "https://accept.paymob.com/api"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

ENVIRONMENT = 'production'

# if ENVIRONMENT == 'development':
#     DEBUG = True
#     ALLOWED_HOSTS=[
#     'furniture-ecommerce-production.up.railway.app',
#     ]
# else:
#     DEBUG = False
#     ALLOWED_HOSTS=[
#     'furniture-ecommerce-production.up.railway.app',
#     ]

POSTGRES_LOCALLY= True
if ENVIRONMENT== 'production' or POSTGRES_LOCALLY== True:
    DATABASES['default']= dj_database_url.parse(config('DATABASE_URL'))