# Generated by Django 5.2.7 on 2025-11-10 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Chairs', 'Chairs'), ('Beds', 'Beds'), ('Accessories', 'Accessories'), ('Furnitures', 'Furnitures'), ('Home Deco', 'Home Deco'), ('Dressings', 'Dressings'), ('Tables', 'Tables')], max_length=100)),
                ('Product_brand', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField(max_length=500)),
                ('Product_color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=100)),
                ('product_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)])),
                ('product_instock', models.BooleanField(default=True)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(upload_to='products/images/')),
            ],
            options={
                'verbose_name': 'Products',
                'ordering': ['-product_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uploaded_image', models.ImageField(upload_to='products/images/%y/%m%d/')),
                ('product_image_date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Images',
                'ordering': ['-product_image_date'],
            },
        ),
    ]
