# Generated by Django 5.2.7 on 2025-11-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_brand',
            field=models.CharField(choices=[('ikea', 'ikea'), ('jysk', 'jysk'), ('b.house', 'b.house'), ('furninova', 'furninova'), ('boffi', 'boffi'), ('cayke', 'cayke'), ('la vie maison', 'la vie maison'), ('abacus', 'abacus'), ('soundofsilence.pl', 'soundofsilence.pl'), ('the apple tree company', 'the apple tree company'), ('cosy maple', 'cosy maple'), ('living in design', 'living in design'), ('de scheidingswandÂ® | the (room) divider', 'de scheidingswandÂ® | the (room) divider'), ('spoty systems', 'spoty systems'), ('third.space', 'third.space'), ('uniters central europe', 'uniters central europe'), ('carpenter & cartwright furniture auctions ltd', 'carpenter & cartwright furniture auctions ltd'), ('the furniture source', 'the furniture source'), ('atelier soudeur', 'atelier soudeur'), ('sorgenfri', 'sorgenfri'), ('meloka', 'meloka'), ('precision office solutions, llc', 'precision office solutions, llc'), ('mfu', 'mfu'), ('honey home co', 'honey home co'), ('studio kulakan', 'studio kulakan'), ('woodnet lifestyles ltd', 'woodnet lifestyles ltd'), ('yeni nesil avm', 'yeni nesil avm'), ('aria design store', 'aria design store'), ('benchtech gmbh', 'benchtech gmbh'), ('furniture wood', 'furniture wood'), ('kalida contract', 'kalida contract'), ('the epoxy legends', 'the epoxy legends'), ('ecf services', 'ecf services'), ('arredamento store', 'arredamento store'), ('esdesk', 'esdesk'), ('mooi art', 'mooi art'), ('collective contract', 'collective contract'), ('muukdesign', 'muukdesign'), ('ciamet', 'ciamet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_uploaded_image',
            field=models.ImageField(upload_to='products/%y/%m/%d/images'),
        ),
    ]
