# Generated by Django 5.2.7 on 2025-11-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_images',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
            preserve_default=False,
        ),
    ]
