# Generated by Django 5.2.7 on 2025-11-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_uploaded_image',
            field=models.ImageField(upload_to='products_image/%y/%m/%d/images'),
        ),
    ]
