# Generated by Django 5.2.7 on 2025-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_uploaded_image',
            field=models.ImageField(upload_to='media/products_image/%y/%m/%d/images'),
        ),
    ]
