# Generated by Django 5.2.7 on 2025-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_product_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_uploaded_image',
            field=models.ImageField(upload_to='products_image/%y/%m/%d/images'),
        ),
    ]
