# Generated by Django 5.2.7 on 2025-11-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_product_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_images',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
        ),
    ]
