# Generated by Django 5.2.7 on 2025-11-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productimage_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_brand',
            new_name='product_brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_color',
            new_name='product_color',
        ),
    ]
