# Generated by Django 5.2.7 on 2025-11-23 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_product_brand_product_product_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(choices=[('Ikea', 'Ikea'), ('Amado', 'Amado'), ('Furniture Inc', 'Furniture Inc'), ('The factory', 'The factory'), ('Artdeco', 'Artdeco')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.PositiveIntegerField(default=1)),
                ('cart_sub_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_delivery_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
