# Generated by Django 5.2.7 on 2025-11-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_product_brand_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['cart_user'], 'verbose_name': 'Cart'},
        ),
    ]
