# Generated by Django 5.2.7 on 2025-11-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
