# Generated by Django 5.2.7 on 2025-12-05 18:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_cart_cart_user_subscribtions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='products_image/%y/%m/%d/'),
        ),
    ]
