# Generated by Django 5.2.7 on 2025-12-05 18:18

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to='products_image/%y/%m/%d/'),
            preserve_default=False,
        ),
    ]
