# Generated by Django 5.2.7 on 2025-12-05 18:42

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_uploaded_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=85, scale=None, size=[1920, 1080], upload_to=''),
        ),
    ]
